name: Deploy

on:
  pull_request:
    branches: [ master ]
  
jobs:

  upload_to_testflight:
    name: Test Flight
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: cs-lucas-costa/Certificados
        token: ${{ secrets.FAKE_REPO_TOKEN }}

    - name: Upload to TestFlight
      run: fastlane beta