name: Deploy

on:
  pull_request:
    branches: [ master ]
  
jobs:

  upload_to_testflight:
    name: Test Flight
    runs-on: macos-latest
    
    steps:
        
    - name: Checkout - Certificados
    - uses: oleksiyrudenko/gha-git-credentials@v2.1
      with:
        global: true
        name: "my-deploy-github"
        email: "deploy.github@gmail.com"
        actor: "my-deploy-github"
        token: ${{ secrets.FAKE_REPO_TOKEN }}

    - name: Set Gems
      run: |
        gem install bundler
        bundle install

    - name: Upload to TestFlight
      run: fastlane beta