name: Deploy

on:
  pull_request:
    branches: [ master ]
  
jobs:

  upload_to_testflight:
    name: Test Flight
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        repository: cs-lucas-costa/Certificados
        ssh-key: ${{ secrets.MATCH_PRIVATE_KEY }}

    - name: Upload to TestFlight
      run: fastlane beta