name: Deploy

on:
  pull_request:
    branches: [ master ]
  
jobs:

  upload_to_testflight:
    name: Test Flight
    runs-on: macos-latest
    
    steps:
        
    - name: Checkout - Certificados
      uses: actions/checkout@v2
      with:
        repository: cs-lucas-costa/Certificados
        token: ${{ secrets.FAKE_REPO_TOKEN }}
        path: 'certificados'

    - name: Checkout - Project
      uses: actions/checkout@v2
      with:
        path: 'main'

    - name: Set Gems
      run: |
        gem install bundler
        bundle install

    - name: Upload to TestFlight
      run: fastlane beta