name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: xcodebuild clean test -project "Bootcamp-Magic.xcodeproj" -scheme "Bootcamp-Magic" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.0"

    - name: Build app
      run: xcodebuild -project 'Bootcamp-Magic.xcodeproj' -scheme 'Bootcamp-Magic' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO