name: CI

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: Build Project
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set Gems
      run: |
        gem install bundler
        bundle install

    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 12.4

    - name: Build app
      run: |
        set -o pipefail
        xcodebuild clean build-for-testing \
        -project 'Bootcamp-Magic.xcodeproj' \
        -scheme 'Bootcamp-Magic' \
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max' \
        | xcpretty 

    - name: Archive derived data artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build


  test:
    name: Test Project
    needs: build
    uses: actions/checkout@v1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    
    - name: Download derived data artifact
      uses: actions/download-artifact@v1
      with:
        name: build

    - name: Set Gems
      run: |
        gem install bundler
        bundle install

    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 12.4

    - name: Run tests
      run: |
        set -o pipefail
        xcodebuild clean test-without-building \
        -project "Bootcamp-Magic.xcodeproj" \
        -scheme "Bootcamp-Magic" \
        -destination "platform=iOS Simulator,name=iPhone 11 Pro Max" \
        | xcpretty


        
    