name: CI

on:
  # push:
    # branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    # - name: Force xcode 11.2.1
    #   run: sudo xcode-select -switch /Applications/Xcode_11.2.1.app

    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 12.4

    - name: Build app
      run: xcodebuild clean build -project 'Bootcamp-Magic.xcodeproj' -scheme 'Bootcamp-Magic' -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'

    - name: Run tests
      run: xcodebuild clean test -project "Bootcamp-Magic.xcodeproj" -scheme "Bootcamp-Magic" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max"

    