name: SwiftLint

  on:
    pull_request:
      types: [opened, synchronize, reopened, edited]
      paths:
       - '**/*.swift'

  jobs:
    lint:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Fetch base ref
          run: git fetch --no-tags --prune --depth=1 origin ${​​​​​{​​​​​ github.base_ref }​​​​​}​​​​​

        - name: SwiftLint
          uses: norio-nomura/action-swiftlint@3.2.1
          env:
            DIFF_BASE: ${​​​​​{​​​​​ github.ref }​​​​​}​​​​​